-- Create a new database for the e-commerce project
CREATE DATABASE  e_commerce;

-- Check total number of records in each table
-- This helps understand dataset size and completeness

SELECT COUNT(*) FROM category_names;   -- total categories
SELECT COUNT(*) FROM customers;        -- total customers
SELECT COUNT(*) FROM geolocation;      -- total location records
SELECT COUNT(*) FROM order_items;      -- total order items
SELECT COUNT(*) FROM orders;           -- total orders
SELECT COUNT(*) FROM payments;         -- total payment records
SELECT COUNT(*) FROM products;         -- total products
SELECT COUNT(*) FROM reviews;          -- total reviews
SELECT COUNT(*) FROM sellers;          -- total sellers


-- Calculate total revenue generated from all orders
-- payment_value represents the amount paid for each transaction
SELECT SUM(payment_value) as total_revenue     -- Total revenue across all payments
FROM payments;


-- Check for orders where delivery date is missing
-- This helps identify orders that are not delivered yet or incomplete
SELECT * FROM orders 
WHERE order_delivered_customer_date IS NULL;

 -- Filter only successfully delivered orders
-- Ensures we are working with valid data for delivery-related analysis
SELECT * FROM orders
WHERE order_status = 'delivered'                     -- Only delivered orders
AND order_delivered_customer_date IS NOT NULL;       -- Delivery date must exist


-- Categorize orders into Delivered and Not Delivered
-- Helps understand overall order completion rate
SELECT 
CASE WHEN order_status = 'delivered'   
THEN 'Delivered'                     -- Successfully delivered orders
ELSE 'Not Delivered' END AS status,
COUNT(*) 							 -- Count of orders in each category
FROM orders
GROUP BY status;



-- Filter reviews where review score is available
SELECT * FROM reviews
WHERE review_score IS NOT NULL;


-- Categorize customer reviews into sentiment groups
-- Helps understand overall customer satisfaction
SELECT 
CASE WHEN review_score >= 4 THEN 'Positive'     -- High ratings (satisfied customers)
WHEN review_score = 3 THEN 'Neutral' 		    -- average experience
ELSE 'Negative'								    -- Low ratings (unsatisfied customers)
END as sentiment,
COUNT(*) AS count
FROM reviews
GROUP BY sentiment
ORDER BY count DESC;

-- Check total orders vs orders with valid delivery date
-- Helps measure data completeness for delivery analysis
SELECT COUNT(*) AS total,                                    -- Total number of orders
COUNT(order_delivered_customer_date) AS non_null_delivery    -- Only non-null delivery dates
FROM orders;

-- Select orders where delivery date is available
SELECT * FROM orders
WHERE order_delivered_customer_date IS NOT NULL;

-- Calculate total revenue generated by each state
-- Join payments, orders, and customers to map revenue to customer location

SELECT 
c.customer_state,					                 -- Customer's state									
SUM(p.payment_value) as revenue			             -- Total revenue from that state
FROM payments p
JOIN orders o ON p.order_id = o.order_id             -- Link payments to orders
JOIN customers c ON o.customer_id = c.customer_id	 -- Link orders to customers (for location)
GROUP BY c.customer_state							 -- Group results by state
ORDER BY revenue DESC limit 10;						 -- Sort from highest to lowest revenue l

-- Calculate revenue generated by each product category
-- Join order_items, products, and category translation table
SELECT 
ct.product_category_name_english,      -- Product category (in English)
SUM(oi.price) as revenue               -- Total revenue from that category
from order_items oi
JOIN products p ON oi.product_id = p.product_id   -- Link order items to products
JOIN category_names ct
ON p.product_category_name = ct.product_category_name   -- Translate category name
GROUP BY ct.product_category_name_english
ORDER BY revenue DESC LIMIT 10;

select * from orders;

-- Analyze impact of delivery performance on customer ratings
-- Compare average review score for late vs on-time deliveries
SELECT 
CASE WHEN o.order_delivered_customer_date > o.order_estimated_delivery_date
THEN 'Late'                   -- Orders delivered after expected date
ELSE 'On Time'                -- Orders delivered on or before expected date
END AS delivery_status,
AVG(r.review_score) as avg_rating    -- Average customer rating
FROM orders o
JOIN reviews r ON o.order_id = r.order_id   -- Join orders with reviews
GROUP BY delivery_status;



-- Analyze how product weight impacts delivery (freight) cost
-- Group products into weight categories and calculate average freight 
SELECT 
CASE WHEN product_weight_g < 500 THEN 'Light'        -- Lightweight products
WHEN product_weight_g BETWEEN 500 AND 2000 THEN 'Medium'  -- Medium weight
ELSE 'Heavy'                                            -- Heavy products
END AS weight_category,
AVG(freight_value) as avg_freight         -- Average delivery cost
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id    -- Join to get product weight
GROUP BY weight_category;                         -- Group by weight category

-- Analyze monthly revenue trend over time
-- Helps understand business growth and seasonality
SELECT 
DATE_TRUNC('month', order_purchase_timestamp) as month,  -- Extract month from order date
SUM(p.payment_value) as revenue                    -- Total revenue for each month
from orders o
JOIN payments p ON o.order_id = p.order_id        -- Join to get payment data
GROUP BY month                                    -- Group by month
ORDER BY month;

-- Identify top customers based on total spending
-- Helps find high-value (VIP) customers
SELECT c.customer_unique_id,    -- Unique customer identifier
SUM(p.payment_value) as total_spent    -- Total amount spent by customer
FROM orders o
JOIN payments p ON o.order_id = p.order_id    -- Join payments with orders
JOIN customers c ON o.customer_id = c.customer_id   -- Map orders to customers
GROUP BY c.customer_unique_id                      -- Group by unique customer
ORDER BY total_spent DESC 
LIMIT 10;

-- Calculate Average Order Value (AOV)
-- Measures average spending per order
SELECT 
sum(payment_value) / COUNT(DISTINCT order_id) as avg_order_value
FROM payments;




-- Calculate average delivery time for completed orders
SELECT 
AVG(order_delivered_customer_date - order_purchase_timestamp) AS Avg_delivery_time   -- Avg time taken to deliver
FROM orders
WHERE order_status = 'delivered';   -- Consider only delivered orders